version: 1.0
uniqNamePart: bd-demo-iam-role
dataSource:
  name: demo
  permissions:
    - urlPrefix: s3://boilingdata-demo/demo
      accessRights:
        - read
    - urlPrefix: s3://isecurefi-dev-test/nyc-tlc/
      accessRights:
        - read
        - write
