/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const EModelFormat = t.enumtype({
  "NDJSON": "ndjson",
  "AVRO": "avro",
  "CSV": "csv",
});

export const EPermission = t.enumtype({
  "READ": "read",
  "WRITE": "write",
});

export const ITemplateSandbox = t.iface([], {
  "name": "string",
  "urlPrefix": "string",
  "uniqNamePart": t.opt("string"),
  "permissions": t.array("EPermission"),
});

export const ITemplateTap = t.iface([], {
  "name": "string",
  "models": t.opt(t.array(t.iface([], {
    "name": "string",
    "model": t.opt(t.array("string")),
    "format": t.opt("EModelFormat"),
  }))),
});

export const ITemplateFlow = t.iface([], {
  "name": "string",
  "input": t.union("string", t.array("string")),
  "keys": t.opt(t.array("string")),
  "transformJs": t.opt("string"),
  "transformSql": t.opt("string"),
  "prefixFunc": t.opt("string"),
  "output": t.opt(t.union("string", t.array("string"))),
  "errors": t.opt("string"),
});

export const ITemplateShare = t.iface([], {
  "name": "string",
  "users": t.array("string"),
  "sql": t.opt("string"),
  "source": t.opt("string"),
  "target": t.opt("string"),
});

export const ITemplate = t.iface([], {
  "version": t.union("string", "number"),
  "name": "string",
  "environment": "string",
  "region": "string",
  "resources": t.iface([], {
    "sandboxes": t.opt(t.array("ITemplateSandbox")),
    "taps": t.opt(t.array("ITemplateTap")),
    "flows": t.opt(t.array("ITemplateFlow")),
    "shares": t.opt(t.array("ITemplateShare")),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  EModelFormat,
  EPermission,
  ITemplateSandbox,
  ITemplateTap,
  ITemplateFlow,
  ITemplateShare,
  ITemplate,
};
export default exportedTypeSuite;
