name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: CI
        run: |
          yarn build
          yarn lint
          yarn test
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
