name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: CI
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn lint
          yarn test
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
